#Site
title: Swift-Man
description: This is Swift-Man' home.
logo: favicon.png
#url: kongsong.me
rss_url: /feed.xml

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Comment
comment:
  disqus: Swift-Man    
  # duoshuo: kongsong
  # youyan: 2122392
  laibili: MTAyMC8zNjIyOS8xMjc2NA==

# Website analytics
#google_analytics: UA-82494501-1
#baidu_analytics: 5b31ffbbdc6cff18727f3adf75a03777    #from //hm.baidu.com/hm.js?***

# Author information:
author:
  #resume: /resume
  name: Swift-Man     #the name of Blog section
  about_me: Swift를 공부하는 Objective-C 개발자입니다. 
  문의사항은 메일로 주세요~
 
# Social Links
email:               jiniopening@naver.com
#google.plus:        username
#twitter:            username
#facebook:            kongsong
#github:              songkong
#stackoverflow:      6438519/song-kong   #from a "http://stackoverflow.com/users/123456/username" link
#linkedin:           kongsong
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
#behance:           username

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile,.sass-cache,.DS_Store,.idea]

theme: jekyll-theme-midnight
